---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-visit-sqs-consumer
spec:
  selector:
    matchLabels:
      app: ip-visit-sqs-consumer
  template:
    metadata:
      labels:
        app: ip-visit-sqs-consumer
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        - name: SQSQUEUENAME
          valueFrom:
            configMapKeyRef:
              name: ip-visit-sqs-consumer
              key: ip_count_queue
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        - name: AWS_DEFAULT_REGION
          value: eu-north-1
        envFrom:
        - configMapRef:
            name: ip-visit-sqs-consumer
        image: ghcr.io/metalbear-co/playground-ip-visit-sqs-consumer:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
        name: main
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
