apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-main
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: registry.k8s.io/redis
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
