---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ip-visit-counter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/ip-visit-counter
    repoURL: https://github.com/metalbear-co/playground
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
