apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - argocd  # Temporarily excluded: CRD annotation size error blocking sync
  - argo-rollouts
  - shared-infra-application.yaml
  - ip-visit-application.yaml
  - ip-visit
  - visualization-application.yaml
  - visualization
  - gateway.yaml
  - namespace.yaml
  - certificate.yaml
