apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../local
- ../../base/ip-visit-sqs-consumer

helmCharts:
  - name: localstack
    repo: https://localstack.github.io/helm-charts
    valuesFile: localstack-values.yaml
    releaseName: localstack
    namespace: localstack

patches:
  - path: localstack-env-vars-patch.yaml
    target:
      kind: Deployment
      name: ip-visit-counter
  - path: localstack-env-vars-patch.yaml
    target:
      kind: Deployment
      name: ip-visit-sqs-consumer
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: SQSQUEUENAME
          value: "IpCount"
    target:
      kind: Deployment
      name: ip-visit-counter

